tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "awscli"
brew "berglas"
brew "colima"
brew "deno"
brew "direnv"
brew "docker"
brew "docker-buildx"
# brew "docker-compose"
brew "docker-credential-helper"
brew "elm"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "gitleaks"
brew "gh"
brew "gnupg"
brew "go"
brew "jq"
brew "nkf"
brew "node"
brew "nodebrew"
brew "pinentry-mac"
brew "poppler"
# brew "postgresql@14"
brew "qpdf"
brew "ripgrep"
brew "tfenv"
brew "tmux"
brew "tree"
brew "unar"
brew "vim"
brew "yarn"
brew "zsh"
# cask "adobe-acrobat-reader"
# cask "adoptopenjdk11"
# cask "discord"
# cask "gather"
# cask "insomnia"
# cask "ngrok"
# cask "sketch"
# cask "sublime-merge"
# cask "vagrant"
# cask "virtualbox"
# cask "wireshark"
cask "1password"
# cask "docker"
cask "google-cloud-sdk"
cask "keycastr"
cask "microsoft-edge"
cask "notion"
cask "raycast"
cask "stoplight-studio"
cask "sublime-text"
# cask "teamflow"
cask "visual-studio-code"
