#!/bin/bash

# Load environment base configuration
[ -f ${HOME}/.bashenv ] && . ${HOME}/.bashenv

: "local bin" && {
	[ -d /usr/local/bin ] && PATH=/usr/local/bin:${PATH}
	[ -d ${HOME}/.local/bin ]   && PATH=${HOME}/.local/bin:${PATH}
	[ -d ${HOME}/esp/xtensa-esp32-elf/bin ] && PATH=${PATH}:${HOME}/esp/xtensa-esp32-elf/bin
}

: "Homebrew" && {
	[ -d /usr/local/Cellar ] && export HOMEBREW_PREFIX=/usr/local
}

: "Java" && {
	readonly javahome=/usr/libexec/java_home
	[ -x $javahome ] && export JAVA_HOME=$($javahome)
	[ -n "$JAVA_HOME" ] && PATH=${PATH}:${JAVA_HOME}/bin
}

: "Go" && {
	[ -d ${HOME}/go ] && export GOPATH=${HOME}/go
	[ -n "$GOPATH" ] && PATH=${PATH}:${GOPATH}/bin
}

: "cargo" && {
	[ -f ${HOME}/.cargo/env ] && . ${HOME}/.cargo/env
}

: "yarn" && {
	# Place where tools installed by `yarn global add` are stored
	export PATH="$HOME/.config/yarn/global/node_modules/.bin:$PATH"
}

: "Export" && {
	export EDITOR=vim
	export PAGER='less -gMj2r'
	[ "${LC_CTYPE}" = "UTF-8" ] && export LC_CTYPE=en_US.UTF-8
	[ -z "${LANG}" ] && export LANG=en_US.UTF-8

	export PATH
}

: "Load bashrc" && {
	[ -f ${HOME}/.bashrc ]	&& . ${HOME}/.bashrc
}

# vim :set filetype=sh syntax=sh:
