" vim: set ts=4 sw=4 sts=0:

" Encoding {{{
set encoding=utf-8
scriptencoding utf-8
set fileencodings=utf-8,cp932,eucjp-ms,iso-2022-jp,latin1
set fileformats=unix,dos,mac

" Deal with some double width characters
if exists('&ambiwidth')
	set ambiwidth=double
endif
" }}}

" Environment {{{
command! VimrcReload source $MYVIMRC
function! VimrcEnvironment ()
	let env = {}
	let env.is_win = has('win32')  || has ('win64')

	let userdir = env.is_win
				\ ? expand('$VIM/vimfiles')
				\ : expand('~/.vim')
	let env.path = {
				\ 'user':        userdir,
				\ 'local_vimrc': userdir . '/.vimrc',
				\ 'tmp':         userdir . '/tmp'
				\ }
	return env
endfunction

function! VimrcSupports ()
	let supports = {}
	return supports
endfunction

let s:env = VimrcEnvironment()
let s:supports = VimrcSupports()
" }}}

" Mapping {{{
" Turn off the IME when escaping from Insert mode @Insert
set timeout timeoutlen=1000 ttimeoutlen=75
inoremap <silent> <ESC> <ESC>:<C-u>set iminsert=0<CR>
" Avoid execute <C-@> @Insert
inoremap <C-@> <Nop>
" Yank to end of the line, like 'D' / 'C' @Normal
nnoremap Y y$
" easier to set nohlsearch
nnoremap <Esc><Esc> :noh<CR>

" Emacs-like keybind @Command-line @Insert
cnoremap <C-a> <Home>
cnoremap <C-e> <End>
cnoremap <C-b> <Left>
cnoremap <C-f> <Right>
cnoremap <C-h> <Backspace>
cnoremap <C-d> <Del>
inoremap <C-h> <Backspace>
inoremap <C-d> <Del>

" Refer to history @Command-line
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>
" }}}

" Misc {{{
set modeline
set showtabline=2

set number
set showmatch
set display=lastline
set virtualedit=block

set wildmenu
set wildmode=list:full
set laststatus=2
set showcmd
set statusline=%<%f\ %m%r%h%w%{'['.(&fenc!=''?&fenc:&enc).']['.&ff.']'}%=%l,%c%V%8P

set nrformats-=octal
set formatoptions& formatoptions+=rmMj
set formatoptions-=q
set whichwrap=b,s,<,>
set backspace=indent,eol

" Backup
set nobackup

" Indent
set noexpandtab
set autoindent
set cindent
set smartindent
set smarttab
set list
set listchars=tab:^\ ,eol:<,trail:_,nbsp:%
set tabstop=4
set shiftwidth=4
set softtabstop=0

" Search
set hlsearch
set noignorecase
set smartcase
set wrapscan
set incsearch

"}}}
if exists('g:acp_enableAtStartup')
	function! InnsertTabWrapper()
		let col = col('.') -1
		if !col || getline('.')[col - 1] !~ '\k'
			return "<\TAB>"
		else
			if pumvisible()
				return "\<C-N>"
			else
				return "\<C-N>\<C-P>"
			end
		endif
	endfunction
endif

"autocmd BufNewFile,BufRead *.php set expandtab tabstop=2 shiftwidth=2
autocmd BufNewFile,BufRead *.html set expandtab tabstop=2 shiftwidth=2
autocmd BufNewFile,BufRead *.css set expandtab tabstop=2 shiftwidth=2
autocmd BufNewFile,BufRead *.js set expandtab tabstop=2 shiftwidth=2

"-----------------------------------------------------------------------------
